export const types = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",

    ADD_ACOUNT: "ADD_ACOUNT",
    READ_ACOUNT: "READ_ACOUNT",
    EDIT_ACOUNT: "EDIT_ACOUNT",

    READ_REGISTER: "READ_REGISTER",
    ADD_REGISTER: "ADD_REGISTER",
    DELETE_REGISTER: "DELETE_REGISTER",
    CLEAN_LOGOUT: "CLEAN_LOGOUT",
  
    RECORD_INCOME: "RECORD_INCOME",
    RECORD_EXPENSE: "RECORD_EXPENSE",
  };